name: 'Glean Collections Sync'
description: 'Automatic syncing of search results into a collection in Glean'
author: 'Steve Calvert'
runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  glean-client-api-url:
    description: 'Glean client API URL'
    required: true
  glean-client-api-token:
    description: 'Glean client API token'
    required: true
  glean-user-email:
    description: 'Glean user email on whose behalf the request is intended to be made'
    required: true
  collection-sync-configs:
    description: 'JSON array of collections, each with name, query, and filters'
    required: true

outputs:
  result:
    description: 'Result of the sync operation'
